-- ADICIONAR COLUNAS PARA CRM NA TABELA DE TAREFAS
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS member_id BIGINT REFERENCES team(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deal_value NUMERIC(12, 2) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Operacional';

-- CRIAR TABELA DE COLUNAS DINÂMICAS PARA O KANBAN
CREATE TABLE IF NOT EXISTS kanban_columns (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  order_index INTEGER NOT NULL,
  color TEXT DEFAULT '#7C3AED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INSERIR COLUNAS PADRÃO (SE NÃO EXISTIREM)
INSERT INTO kanban_columns (name, order_index, color)
VALUES 
('A Fazer', 1, '#64748B'),
('Em Progresso', 2, '#3B82F6'),
('Concluído', 3, '#10B981')
ON CONFLICT (name) DO NOTHING;

-- ATUALIZAR TABELA DE CLIENTES PARA CRM MAIS ROBUSTO
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS company_size TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS lead_status TEXT DEFAULT 'Lead'; -- ['Lead', 'Oportunidade', 'Cliente', 'Inativo']

-- ATUALIZAR TABELA DE TIME
ALTER TABLE team ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE team ADD COLUMN IF NOT EXISTS phone TEXT;
